version: '3.9'

services:
  db:
    image: postgres:15
    container_name: investiq_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Arhip2010
      POSTGRES_DB: investiq
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./
    container_name: investiq_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_URL: postgresql+asyncpg://postgres:Arhip2010@db:5432/investiq


volumes:
  postgres_data: