"""del type field in category

Revision ID: 6bbdd1d891e4
Revises: d2a4b2669e50
Create Date: 2026-02-22 20:51:43.359258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbdd1d891e4'
down_revision: Union[str, Sequence[str], None] = 'd2a4b2669e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
