"""change budget to decimal

Revision ID: d921db2b7473
Revises: db946b6769df
Create Date: 2026-03-11 11:27:57.419848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd921db2b7473'
down_revision: Union[str, Sequence[str], None] = 'db946b6769df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'budget',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'budget',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=7, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
