"""change budget to decimal

Revision ID: db946b6769df
Revises: fd2b195ad161
Create Date: 2026-03-11 11:25:52.432806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db946b6769df'
down_revision: Union[str, Sequence[str], None] = 'fd2b195ad161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'budget',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'budget',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
